name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  EXILED_REFERENCES_PATH: ${{ github.workspace }}/RemoteKeycard/lib

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Nuget
        uses: iRebbok/setup-nuget@master

      - name: Restore Packages
        run: nuget restore RemoteKeycard.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Download references
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://exmod-team.github.io/SL-References/Dev.zip'
          file-name: 'References.zip'

      - name: Extract Refs
        run: |
          mkdir RemoteKeycard\lib
          tar -xf References.zip -C RemoteKeycard/lib

      - name: Build
        env:
          EXILED_REFERENCES: ${{ env.EXILED_REFERENCES_PATH }}
        run: msbuild RemoteKeycard.sln -p:Configuration=EXILED

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: Plugin DLL
          path: RemoteKeycard\bin\Release\RemoteKeycard*.dll
